services:
  # --- INGRESS & SECRETS ---
  traefik:
    image: traefik:v3.7
    container_name: tourmaline-traefik
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "80:80"
      - "8082:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./infra/traefik/traefik.yml:/etc/traefik/traefik.yml:ro

  # vault:
  #   image: hashicorp/vault:latest
  #   container_name: tourmaline-vault
  #   command: ["vault", "server", "-config=/vault/config/local.json"]
  #   ports:
  #     - "8200:8200"
  #   volumes:
  #     - vault_data:/vault/file
  #     - ./infra/vault/config:/vault/config
  #   cap_add:
  #     - IPC_LOCK

  # --- IDENTITY & ACCESS MANAGEMENT (IAM) ---
  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: tourmaline-keycloak
    command: start-dev
    ports:
      - "8081:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin_password
      # PostgreSQL configuration for Keycloak
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/tourmaline_db
      KC_DB_USERNAME: tourmaline
      KC_DB_PASSWORD: tourmaline_pass
      KC_DB_SCHEMA: keycloak
    depends_on:
      - postgres

  # --- FRONTEND (ENTRY POINT) ---
  # web-frontend:
  #   build:
  #     context: ./apps/web
  #     dockerfile: Dockerfile
  #   container_name: tourmaline-web-frontend
  #   ports:
  #     - "3000:8080"
  #   environment:
  #     - NEXT_PUBLIC_API_GATEWAY_URL=http://localhost:8000
  #   depends_on:
  #     - api-gateway

  # --- DATABASES & BROKERS ---
  postgres:
    image: postgres:18.6-alpine
    container_name: tourmaline-postgres
    restart: always
    environment:
      POSTGRES_USER: tourmaline
      POSTGRES_PASSWORD: tourmaline_pass
      POSTGRES_DB: tourmaline_db
      PGDATA: /var/lib/postgresql/data/18
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    shm_size: 128mb

  redis:
    image: redis:8-alpine
    container_name: tourmaline-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: tourmaline-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  # --- OBSERVABILITY ---
  prometheus:
    image: prom/prometheus:latest
    container_name: tourmaline-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:latest
    container_name: tourmaline-grafana
    ports:
      - "8083:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  pgdata:
    driver: local
  vault_data:
    driver: local
