module(
    name = "tourmaline",
    version = "0.1.0",
)

# --- Go Rules & Toolchain ---
bazel_dep(name = "rules_go", version = "0.64.2")
bazel_dep(name = "gazelle", version = "2.0.0-beta.1")

go_sdk = use_extension("@rules_go//go:extensions.bzl", "go_sdk")
go_sdk.download(version = "1.27.1")

go_deps = use_extension("@gazelle//:extensions.bzl", "go_deps")
go_deps.from_file(go_mod = "//:go.mod")

# --- Protobuf & gRPC Rules ---
bazel_dep(name = "protobuf", version = "36.2")
